### ISSUE TITLE
Flutter 카메라 샘플 앱 만들기

### ISSUE THREAD

**Issue by suminies** [GlobalMediaBridge/cosmetic-server#11]
Flutter로 내장된 카메라 사용하기
https://flutter-ko.dev/docs/cookbook/plugins/picture-using-camera

**Comment by ParkEunwoo** [comment]
https://www.raywenderlich.com/4333657-using-the-camera-on-flutter

**Comment by ParkEunwoo** [comment]
카메라 촬영 후 확인 선택 시 촬영된 이미지를 다음 페이지로 전달해서 보여주기

**Comment by ParkEunwoo** [comment]
카메라 연동까지 완료
